<?php
/**
 * DesignTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Tweak\Api
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * tweak-api
 *
 * Tweak API to integrate with all the Tweak services.  You can find out more about Tweak      at <a href='https://www.tweak.com'>https://www.tweak.com</a>, #tweak.
 *
 * OpenAPI spec version: 1.0.8-alpha.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Tweak\Api;

/**
 * DesignTest Class Doc Comment
 *
 * @category    Class */
// * @description Design
/**
 * @package     Tweak\Api
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DesignTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Design"
     */
    public function testDesign()
    {

    }

    /**
     * Test attribute "colors"
     */
    public function testPropertyColors()
    {

    }

    /**
     * Test attribute "image"
     */
    public function testPropertyImage()
    {

    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {

    }

    /**
     * Test attribute "object"
     */
    public function testPropertyObject()
    {

    }

    /**
     * Test attribute "thumbnail"
     */
    public function testPropertyThumbnail()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "purpose"
     */
    public function testPropertyPurpose()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "formData"
     */
    public function testPropertyFormData()
    {

    }

    /**
     * Test attribute "highResPdfUrl"
     */
    public function testPropertyHighResPdfUrl()
    {

    }

    /**
     * Test attribute "proofPdfUrl"
     */
    public function testPropertyProofPdfUrl()
    {

    }

    /**
     * Test attribute "jpegsUrl"
     */
    public function testPropertyJpegsUrl()
    {

    }

    /**
     * Test attribute "edited"
     */
    public function testPropertyEdited()
    {

    }

    /**
     * Test attribute "expired"
     */
    public function testPropertyExpired()
    {

    }

    /**
     * Test attribute "path"
     */
    public function testPropertyPath()
    {

    }

    /**
     * Test attribute "sentForApproval"
     */
    public function testPropertySentForApproval()
    {

    }

    /**
     * Test attribute "approved"
     */
    public function testPropertyApproved()
    {

    }

    /**
     * Test attribute "shared"
     */
    public function testPropertyShared()
    {

    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {

    }

    /**
     * Test attribute "modified"
     */
    public function testPropertyModified()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "dynamicDataId"
     */
    public function testPropertyDynamicDataId()
    {

    }

    /**
     * Test attribute "teamId"
     */
    public function testPropertyTeamId()
    {

    }

    /**
     * Test attribute "requesterId"
     */
    public function testPropertyRequesterId()
    {

    }

    /**
     * Test attribute "assigneeId"
     */
    public function testPropertyAssigneeId()
    {

    }

    /**
     * Test attribute "reviewerId"
     */
    public function testPropertyReviewerId()
    {

    }

    /**
     * Test attribute "templateId"
     */
    public function testPropertyTemplateId()
    {

    }

    /**
     * Test attribute "portalId"
     */
    public function testPropertyPortalId()
    {

    }

    /**
     * Test attribute "rejectionCommentId"
     */
    public function testPropertyRejectionCommentId()
    {

    }

    /**
     * Test attribute "folderId"
     */
    public function testPropertyFolderId()
    {

    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {

    }

    /**
     * Test attribute "template"
     */
    public function testPropertyTemplate()
    {

    }

    /**
     * Test attribute "portal"
     */
    public function testPropertyPortal()
    {

    }

    /**
     * Test attribute "team"
     */
    public function testPropertyTeam()
    {

    }

    /**
     * Test attribute "comments"
     */
    public function testPropertyComments()
    {

    }

    /**
     * Test attribute "rejectionComment"
     */
    public function testPropertyRejectionComment()
    {

    }

    /**
     * Test attribute "exports"
     */
    public function testPropertyExports()
    {

    }

    /**
     * Test attribute "requester"
     */
    public function testPropertyRequester()
    {

    }

    /**
     * Test attribute "assignee"
     */
    public function testPropertyAssignee()
    {

    }

    /**
     * Test attribute "reviewer"
     */
    public function testPropertyReviewer()
    {

    }

    /**
     * Test attribute "commenters"
     */
    public function testPropertyCommenters()
    {

    }

    /**
     * Test attribute "folder"
     */
    public function testPropertyFolder()
    {

    }

    /**
     * Test attribute "permission"
     */
    public function testPropertyPermission()
    {

    }

    /**
     * Test attribute "members"
     */
    public function testPropertyMembers()
    {

    }

    /**
     * Test attribute "designMembers"
     */
    public function testPropertyDesignMembers()
    {

    }

    /**
     * Test attribute "dynamicData"
     */
    public function testPropertyDynamicData()
    {

    }

}
