<?php
/**
 * PortalTemplateApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Tweak\Api
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * tweak-api
 *
 * Tweak API to integrate with all the Tweak services.  You can find out more about Tweak      at <a href='https://www.tweak.com'>https://www.tweak.com</a>, #tweak.
 *
 * OpenAPI spec version: 1.0.2-alpha.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Tweak\Api;

use \Tweak\Api\Configuration;
use \Tweak\Api\ApiClient;
use \Tweak\Api\ApiException;
use \Tweak\Api\ObjectSerializer;

/**
 * PortalTemplateApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tweak\Api
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PortalTemplateApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for portalTemplatesChangeStreamGet
     *
     * Create a change stream..
     *
     */
    public function testPortalTemplatesChangeStreamGet()
    {

    }

    /**
     * Test case for portalTemplatesChangeStreamPost
     *
     * Create a change stream..
     *
     */
    public function testPortalTemplatesChangeStreamPost()
    {

    }

    /**
     * Test case for portalTemplatesCountGet
     *
     * Count instances of the model matched by where from the data source..
     *
     */
    public function testPortalTemplatesCountGet()
    {

    }

    /**
     * Test case for portalTemplatesFindOneGet
     *
     * Find first instance of the model matched by filter from the data source..
     *
     */
    public function testPortalTemplatesFindOneGet()
    {

    }

    /**
     * Test case for portalTemplatesGet
     *
     * Find all instances of the model matched by filter from the data source..
     *
     */
    public function testPortalTemplatesGet()
    {

    }

    /**
     * Test case for portalTemplatesIdDelete
     *
     * Delete a model instance by {{id}} from the data source..
     *
     */
    public function testPortalTemplatesIdDelete()
    {

    }

    /**
     * Test case for portalTemplatesIdExistsGet
     *
     * Check whether a model instance exists in the data source..
     *
     */
    public function testPortalTemplatesIdExistsGet()
    {

    }

    /**
     * Test case for portalTemplatesIdFolderGet
     *
     * Fetches belongsTo relation folder..
     *
     */
    public function testPortalTemplatesIdFolderGet()
    {

    }

    /**
     * Test case for portalTemplatesIdGet
     *
     * Find a model instance by {{id}} from the data source..
     *
     */
    public function testPortalTemplatesIdGet()
    {

    }

    /**
     * Test case for portalTemplatesIdHead
     *
     * Check whether a model instance exists in the data source..
     *
     */
    public function testPortalTemplatesIdHead()
    {

    }

    /**
     * Test case for portalTemplatesIdPatch
     *
     * Patch attributes for a model instance and persist it into the data source..
     *
     */
    public function testPortalTemplatesIdPatch()
    {

    }

    /**
     * Test case for portalTemplatesIdPortalGet
     *
     * Fetches belongsTo relation portal..
     *
     */
    public function testPortalTemplatesIdPortalGet()
    {

    }

    /**
     * Test case for portalTemplatesIdPut
     *
     * Replace attributes for a model instance and persist it into the data source..
     *
     */
    public function testPortalTemplatesIdPut()
    {

    }

    /**
     * Test case for portalTemplatesIdReplacePost
     *
     * Replace attributes for a model instance and persist it into the data source..
     *
     */
    public function testPortalTemplatesIdReplacePost()
    {

    }

    /**
     * Test case for portalTemplatesIdTemplateGet
     *
     * Fetches belongsTo relation template..
     *
     */
    public function testPortalTemplatesIdTemplateGet()
    {

    }

    /**
     * Test case for portalTemplatesPatch
     *
     * Patch an existing model instance or insert a new one into the data source..
     *
     */
    public function testPortalTemplatesPatch()
    {

    }

    /**
     * Test case for portalTemplatesPost
     *
     * Create a new instance of the model and persist it into the data source..
     *
     */
    public function testPortalTemplatesPost()
    {

    }

    /**
     * Test case for portalTemplatesPut
     *
     * Replace an existing model instance or insert a new one into the data source..
     *
     */
    public function testPortalTemplatesPut()
    {

    }

    /**
     * Test case for portalTemplatesReplaceOrCreatePost
     *
     * Replace an existing model instance or insert a new one into the data source..
     *
     */
    public function testPortalTemplatesReplaceOrCreatePost()
    {

    }

    /**
     * Test case for portalTemplatesUpdatePost
     *
     * Update instances of the model matched by {{where}} from the data source..
     *
     */
    public function testPortalTemplatesUpdatePost()
    {

    }

    /**
     * Test case for portalTemplatesUpsertWithWherePost
     *
     * Update an existing model instance or insert a new one into the data source based on the where criteria..
     *
     */
    public function testPortalTemplatesUpsertWithWherePost()
    {

    }

}
