<?php
/**
 * ProductMaterialApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Tweak\Api
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * tweak-api
 *
 * Tweak API to integrate with all the Tweak services.  You can find out more about Tweak      at <a href='https://www.tweak.com'>https://www.tweak.com</a>, #tweak.
 *
 * OpenAPI spec version: 1.0.7-beta.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Tweak\Api;

use \Tweak\Api\Configuration;
use \Tweak\Api\ApiClient;
use \Tweak\Api\ApiException;
use \Tweak\Api\ObjectSerializer;

/**
 * ProductMaterialApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tweak\Api
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ProductMaterialApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for productMaterialsChangeStreamGet
     *
     * Create a change stream..
     *
     */
    public function testProductMaterialsChangeStreamGet()
    {

    }

    /**
     * Test case for productMaterialsChangeStreamPost
     *
     * Create a change stream..
     *
     */
    public function testProductMaterialsChangeStreamPost()
    {

    }

    /**
     * Test case for productMaterialsCountGet
     *
     * Count instances of the model matched by where from the data source..
     *
     */
    public function testProductMaterialsCountGet()
    {

    }

    /**
     * Test case for productMaterialsFindOneGet
     *
     * Find first instance of the model matched by filter from the data source..
     *
     */
    public function testProductMaterialsFindOneGet()
    {

    }

    /**
     * Test case for productMaterialsGet
     *
     * Find all instances of the model matched by filter from the data source..
     *
     */
    public function testProductMaterialsGet()
    {

    }

    /**
     * Test case for productMaterialsIdDelete
     *
     * Delete a model instance by {{id}} from the data source..
     *
     */
    public function testProductMaterialsIdDelete()
    {

    }

    /**
     * Test case for productMaterialsIdExistsGet
     *
     * Check whether a model instance exists in the data source..
     *
     */
    public function testProductMaterialsIdExistsGet()
    {

    }

    /**
     * Test case for productMaterialsIdGet
     *
     * Find a model instance by {{id}} from the data source..
     *
     */
    public function testProductMaterialsIdGet()
    {

    }

    /**
     * Test case for productMaterialsIdHead
     *
     * Check whether a model instance exists in the data source..
     *
     */
    public function testProductMaterialsIdHead()
    {

    }

    /**
     * Test case for productMaterialsIdPatch
     *
     * Patch attributes for a model instance and persist it into the data source..
     *
     */
    public function testProductMaterialsIdPatch()
    {

    }

    /**
     * Test case for productMaterialsIdPut
     *
     * Replace attributes for a model instance and persist it into the data source..
     *
     */
    public function testProductMaterialsIdPut()
    {

    }

    /**
     * Test case for productMaterialsIdReplacePost
     *
     * Replace attributes for a model instance and persist it into the data source..
     *
     */
    public function testProductMaterialsIdReplacePost()
    {

    }

    /**
     * Test case for productMaterialsIdTeamGet
     *
     * Fetches belongsTo relation team..
     *
     */
    public function testProductMaterialsIdTeamGet()
    {

    }

    /**
     * Test case for productMaterialsPatch
     *
     * Patch an existing model instance or insert a new one into the data source..
     *
     */
    public function testProductMaterialsPatch()
    {

    }

    /**
     * Test case for productMaterialsPost
     *
     * Create a new instance of the model and persist it into the data source..
     *
     */
    public function testProductMaterialsPost()
    {

    }

    /**
     * Test case for productMaterialsPut
     *
     * Replace an existing model instance or insert a new one into the data source..
     *
     */
    public function testProductMaterialsPut()
    {

    }

    /**
     * Test case for productMaterialsReplaceOrCreatePost
     *
     * Replace an existing model instance or insert a new one into the data source..
     *
     */
    public function testProductMaterialsReplaceOrCreatePost()
    {

    }

    /**
     * Test case for productMaterialsUpdatePost
     *
     * Update instances of the model matched by {{where}} from the data source..
     *
     */
    public function testProductMaterialsUpdatePost()
    {

    }

    /**
     * Test case for productMaterialsUpsertWithWherePost
     *
     * Update an existing model instance or insert a new one into the data source based on the where criteria..
     *
     */
    public function testProductMaterialsUpsertWithWherePost()
    {

    }

}
