<?php
/**
 * TeamBuilderConfigProductGroupApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Tweak\Api
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * tweak-api
 *
 * Tweak API to integrate with all the Tweak services.  You can find out more about Tweak      at <a href='https://www.tweak.com'>https://www.tweak.com</a>, #tweak.
 *
 * OpenAPI spec version: 1.0.3-alpha.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Tweak\Api;

use \Tweak\Api\Configuration;
use \Tweak\Api\ApiClient;
use \Tweak\Api\ApiException;
use \Tweak\Api\ObjectSerializer;

/**
 * TeamBuilderConfigProductGroupApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tweak\Api
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TeamBuilderConfigProductGroupApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsChangeStreamGet
     *
     * Create a change stream..
     *
     */
    public function testTeamBuilderConfigProductGroupsChangeStreamGet()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsChangeStreamPost
     *
     * Create a change stream..
     *
     */
    public function testTeamBuilderConfigProductGroupsChangeStreamPost()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsCountGet
     *
     * Count instances of the model matched by where from the data source..
     *
     */
    public function testTeamBuilderConfigProductGroupsCountGet()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsFindOneGet
     *
     * Find first instance of the model matched by filter from the data source..
     *
     */
    public function testTeamBuilderConfigProductGroupsFindOneGet()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsGet
     *
     * Find all instances of the model matched by filter from the data source..
     *
     */
    public function testTeamBuilderConfigProductGroupsGet()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsIdBuilderConfigGet
     *
     * Fetches belongsTo relation builderConfig..
     *
     */
    public function testTeamBuilderConfigProductGroupsIdBuilderConfigGet()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsIdDelete
     *
     * Delete a model instance by {{id}} from the data source..
     *
     */
    public function testTeamBuilderConfigProductGroupsIdDelete()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsIdExistsGet
     *
     * Check whether a model instance exists in the data source..
     *
     */
    public function testTeamBuilderConfigProductGroupsIdExistsGet()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsIdGet
     *
     * Find a model instance by {{id}} from the data source..
     *
     */
    public function testTeamBuilderConfigProductGroupsIdGet()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsIdHead
     *
     * Check whether a model instance exists in the data source..
     *
     */
    public function testTeamBuilderConfigProductGroupsIdHead()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsIdPatch
     *
     * Patch attributes for a model instance and persist it into the data source..
     *
     */
    public function testTeamBuilderConfigProductGroupsIdPatch()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsIdProductGroupGet
     *
     * Fetches belongsTo relation productGroup..
     *
     */
    public function testTeamBuilderConfigProductGroupsIdProductGroupGet()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsIdPut
     *
     * Replace attributes for a model instance and persist it into the data source..
     *
     */
    public function testTeamBuilderConfigProductGroupsIdPut()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsIdReplacePost
     *
     * Replace attributes for a model instance and persist it into the data source..
     *
     */
    public function testTeamBuilderConfigProductGroupsIdReplacePost()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsPatch
     *
     * Patch an existing model instance or insert a new one into the data source..
     *
     */
    public function testTeamBuilderConfigProductGroupsPatch()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsPost
     *
     * Create a new instance of the model and persist it into the data source..
     *
     */
    public function testTeamBuilderConfigProductGroupsPost()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsPut
     *
     * Replace an existing model instance or insert a new one into the data source..
     *
     */
    public function testTeamBuilderConfigProductGroupsPut()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsReplaceOrCreatePost
     *
     * Replace an existing model instance or insert a new one into the data source..
     *
     */
    public function testTeamBuilderConfigProductGroupsReplaceOrCreatePost()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsUpdatePost
     *
     * Update instances of the model matched by {{where}} from the data source..
     *
     */
    public function testTeamBuilderConfigProductGroupsUpdatePost()
    {

    }

    /**
     * Test case for teamBuilderConfigProductGroupsUpsertWithWherePost
     *
     * Update an existing model instance or insert a new one into the data source based on the where criteria..
     *
     */
    public function testTeamBuilderConfigProductGroupsUpsertWithWherePost()
    {

    }

}
